/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnitIdRouteImport } from './routes/unit.$id'
import { Route as InquiryIdRouteImport } from './routes/inquiry.$id'
import { Route as DemoEmailInternalRouteImport } from './routes/demo.email-internal'
import { Route as DemoEmailApplicantRouteImport } from './routes/demo.email-applicant'

const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitIdRoute = UnitIdRouteImport.update({
  id: '/unit/$id',
  path: '/unit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiryIdRoute = InquiryIdRouteImport.update({
  id: '/inquiry/$id',
  path: '/inquiry/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoEmailInternalRoute = DemoEmailInternalRouteImport.update({
  id: '/demo/email-internal',
  path: '/demo/email-internal',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoEmailApplicantRoute = DemoEmailApplicantRouteImport.update({
  id: '/demo/email-applicant',
  path: '/demo/email-applicant',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/confirmation': typeof ConfirmationRoute
  '/demo/email-applicant': typeof DemoEmailApplicantRoute
  '/demo/email-internal': typeof DemoEmailInternalRoute
  '/inquiry/$id': typeof InquiryIdRoute
  '/unit/$id': typeof UnitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/confirmation': typeof ConfirmationRoute
  '/demo/email-applicant': typeof DemoEmailApplicantRoute
  '/demo/email-internal': typeof DemoEmailInternalRoute
  '/inquiry/$id': typeof InquiryIdRoute
  '/unit/$id': typeof UnitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/confirmation': typeof ConfirmationRoute
  '/demo/email-applicant': typeof DemoEmailApplicantRoute
  '/demo/email-internal': typeof DemoEmailInternalRoute
  '/inquiry/$id': typeof InquiryIdRoute
  '/unit/$id': typeof UnitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/confirmation'
    | '/demo/email-applicant'
    | '/demo/email-internal'
    | '/inquiry/$id'
    | '/unit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/confirmation'
    | '/demo/email-applicant'
    | '/demo/email-internal'
    | '/inquiry/$id'
    | '/unit/$id'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/confirmation'
    | '/demo/email-applicant'
    | '/demo/email-internal'
    | '/inquiry/$id'
    | '/unit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  ConfirmationRoute: typeof ConfirmationRoute
  DemoEmailApplicantRoute: typeof DemoEmailApplicantRoute
  DemoEmailInternalRoute: typeof DemoEmailInternalRoute
  InquiryIdRoute: typeof InquiryIdRoute
  UnitIdRoute: typeof UnitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unit/$id': {
      id: '/unit/$id'
      path: '/unit/$id'
      fullPath: '/unit/$id'
      preLoaderRoute: typeof UnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiry/$id': {
      id: '/inquiry/$id'
      path: '/inquiry/$id'
      fullPath: '/inquiry/$id'
      preLoaderRoute: typeof InquiryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/email-internal': {
      id: '/demo/email-internal'
      path: '/demo/email-internal'
      fullPath: '/demo/email-internal'
      preLoaderRoute: typeof DemoEmailInternalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/email-applicant': {
      id: '/demo/email-applicant'
      path: '/demo/email-applicant'
      fullPath: '/demo/email-applicant'
      preLoaderRoute: typeof DemoEmailApplicantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  ConfirmationRoute: ConfirmationRoute,
  DemoEmailApplicantRoute: DemoEmailApplicantRoute,
  DemoEmailInternalRoute: DemoEmailInternalRoute,
  InquiryIdRoute: InquiryIdRoute,
  UnitIdRoute: UnitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
